spring.application.name=register
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/local_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=sapassword

spring.jpa.hibernate.ddl-auto=create

# ? QUAN TR?NG (fix l?i c?a b?n)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect